[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
  'npm ci',
  'npx prisma generate'
]

[phases.build]
cmds = ['npx tsc']

[start]
cmd = 'npx prisma migrate deploy && node dist/server.js'